# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProxPics' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProxPics
pod 'TensorFlowLiteSwift'
    pod 'SwiftyBeaver'
    pod 'PopupDialog'
    pod 'SwiftSpinner'
pod "RSLoadingView"

end
